
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=G7h&3jK9#lM2$nP
spring.datasource.driver-class-name=org.postgresql.Driver
spring.h2.console.enabled=true
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
jwt.secret=${JWT_SECRET_KEY:KEY_VALUE}
jwt.expiration=${JWT_EXPIRATION:86400000}